# Generated by Django 4.2.5 on 2023-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, upload_to='static/images/'),
        ),
    ]
