# Generated by Django 4.2.5 on 2023-09-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_getimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GetImage',
        ),
    ]
